/**
 * Robots.txt Manager
 * Generate and manage robots.txt with SEO best practices
 */

export interface RobotsTxtConfig {
  userAgents: UserAgentRule[];
  sitemaps: string[];
  customRules?: string;
}

export interface UserAgentRule {
  userAgent: string;
  allow?: string[];
  disallow?: string[];
  crawlDelay?: number;
}

export function generateRobotsTxt(config: RobotsTxtConfig, platform: "wordpress" | "woocommerce"): string {
  let content = "# Robots.txt generated by SEO Max\n";
  content += `# Platform: ${platform}\n`;
  content += `# Generated: ${new Date().toISOString()}\n\n`;

  // User agents
  for (const rule of config.userAgents) {
    content += `User-agent: ${rule.userAgent}\n`;

    if (rule.allow && rule.allow.length > 0) {
      for (const path of rule.allow) {
        content += `Allow: ${path}\n`;
      }
    }

    if (rule.disallow && rule.disallow.length > 0) {
      for (const path of rule.disallow) {
        content += `Disallow: ${path}\n`;
      }
    }

    if (rule.crawlDelay) {
      content += `Crawl-delay: ${rule.crawlDelay}\n`;
    }

    content += "\n";
  }

  // Sitemaps
  for (const sitemap of config.sitemaps) {
    content += `Sitemap: ${sitemap}\n`;
  }

  // Custom rules
  if (config.customRules) {
    content += "\n# Custom Rules\n";
    content += config.customRules;
  }

  return content;
}

export function getDefaultWooCommerceRobotsTxt(siteUrl: string): RobotsTxtConfig {
  return {
    userAgents: [
      {
        userAgent: "*",
        allow: [
          "/wp-content/uploads/",
          "/wp-content/themes/*/assets/",
        ],
        disallow: [
          "/wp-admin/",
          "/wp-includes/",
          "/wp-content/plugins/",
          "/cart/",
          "/checkout/",
          "/my-account/",
          "/wc-api/",
          "/?add-to-cart=",
          "/?removed_item=",
          "/?orderby=",
          "/?s=",
          "/?filter_",
          "/xmlrpc.php",
          "/wp-login.php",
          "/wp-register.php",
          "/trackback/",
          "/feed/",
          "/comments/feed/",
          "*/feed/$",
          "*/trackback/$",
          "*/attachment/$",
          "*/embed/$",
          "*/page/",
        ],
      },
      {
        userAgent: "Googlebot",
        allow: ["/"],
        crawlDelay: 0,
      },
      {
        userAgent: "Googlebot-Image",
        allow: [
          "/wp-content/uploads/",
        ],
      },
      {
        userAgent: "AhrefsBot",
        disallow: ["/"],
        crawlDelay: 10,
      },
      {
        userAgent: "SemrushBot",
        disallow: ["/"],
        crawlDelay: 10,
      },
    ],
    sitemaps: [
      `${siteUrl}/sitemap_index.xml`,
      `${siteUrl}/wp-sitemap.xml`,
    ],
  };
}

export function validateRobotsTxt(content: string): {
  isValid: boolean;
  errors: string[];
  warnings: string[];
  suggestions: string[];
} {
  const errors: string[] = [];
  const warnings: string[] = [];
  const suggestions: string[] = [];

  const lines = content.split("\n");
  let hasUserAgent = false;
  let hasSitemap = false;
  let currentUserAgent = "";

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    const lineNum = i + 1;

    if (line.startsWith("#") || line === "") continue;

    // User-agent check
    if (line.toLowerCase().startsWith("user-agent:")) {
      hasUserAgent = true;
      currentUserAgent = line.split(":")[1]?.trim() || "";
      
      if (!currentUserAgent) {
        errors.push(`Line ${lineNum}: User-agent value is empty`);
      }
    }

    // Sitemap check
    if (line.toLowerCase().startsWith("sitemap:")) {
      hasSitemap = true;
      const sitemapUrl = line.split(":").slice(1).join(":").trim();
      
      if (!sitemapUrl.startsWith("http")) {
        errors.push(`Line ${lineNum}: Sitemap must be a full URL (including http/https)`);
      }
    }

    // Disallow check
    if (line.toLowerCase().startsWith("disallow:")) {
      const path = line.split(":")[1]?.trim();
      
      if (path === undefined) {
        errors.push(`Line ${lineNum}: Disallow path is missing`);
      }
      
      if (!currentUserAgent) {
        errors.push(`Line ${lineNum}: Disallow must come after User-agent`);
      }
    }

    // Allow check
    if (line.toLowerCase().startsWith("allow:")) {
      if (!currentUserAgent) {
        errors.push(`Line ${lineNum}: Allow must come after User-agent`);
      }
    }

    // Crawl-delay check
    if (line.toLowerCase().startsWith("crawl-delay:")) {
      const delay = line.split(":")[1]?.trim();
      
      if (delay && isNaN(Number(delay))) {
        errors.push(`Line ${lineNum}: Crawl-delay must be a number`);
      }
    }

    // Unknown directive
    const knownDirectives = ["user-agent", "allow", "disallow", "sitemap", "crawl-delay", "host"];
    const directive = line.split(":")[0]?.toLowerCase();
    
    if (directive && !knownDirectives.includes(directive)) {
      warnings.push(`Line ${lineNum}: Unknown directive '${directive}'`);
    }
  }

  if (!hasUserAgent) {
    errors.push("No User-agent directive found");
  }

  if (!hasSitemap) {
    warnings.push("No Sitemap directive found - consider adding sitemap URL");
  }

  // Check for common WooCommerce paths
  const contentLower = content.toLowerCase();
  
  if (!contentLower.includes("/cart/")) {
    suggestions.push("Consider blocking /cart/ to prevent indexing");
  }

  if (!contentLower.includes("/checkout/")) {
    suggestions.push("Consider blocking /checkout/ to prevent indexing");
  }

  if (!contentLower.includes("/my-account/")) {
    suggestions.push("Consider blocking /my-account/ to prevent indexing");
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
    suggestions,
  };
}

// Check if specific path is blocked
export function isPathBlocked(robotsTxtContent: string, path: string, userAgent: string = "*"): boolean {
  const lines = robotsTxtContent.split("\n");
  let currentUserAgent = "";
  let allows: string[] = [];
  let disallows: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    
    if (trimmed.toLowerCase().startsWith("user-agent:")) {
      // Process previous user agent
      if (currentUserAgent === userAgent || currentUserAgent === "*") {
        // Check if path matches any disallow (and not overridden by allow)
        for (const disallow of disallows) {
          if (path.startsWith(disallow)) {
            const moreSpecificAllow = allows.some((allow) => path.startsWith(allow) && allow.length > disallow.length);
            if (!moreSpecificAllow) return true;
          }
        }
      }

      currentUserAgent = trimmed.split(":")[1]?.trim() || "";
      allows = [];
      disallows = [];
    }

    if (currentUserAgent === userAgent || currentUserAgent === "*") {
      if (trimmed.toLowerCase().startsWith("allow:")) {
        const allowPath = trimmed.split(":")[1]?.trim();
        if (allowPath) allows.push(allowPath);
      }

      if (trimmed.toLowerCase().startsWith("disallow:")) {
        const disallowPath = trimmed.split(":")[1]?.trim();
        if (disallowPath) disallows.push(disallowPath);
      }
    }
  }

  return false;
}
