"use client";

import { useState } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Clock,
  FileText,
  Image,
  MessageSquare,
  Sparkles,
  Zap,
} from "lucide-react";
import { ContentFreshnessTab } from "./content-freshness-tab";
import { ThinContentTab } from "./thin-content-tab";
import { ImageOptimizationTab } from "./image-optimization-tab";
import { FAQGenerationTab } from "./faq-generation-tab";

interface ImprovementsDashboardProps {
  storeId: string;
  storeUrl: string;
}

export function ImprovementsDashboard({
  storeId,
  storeUrl,
}: ImprovementsDashboardProps) {
  const [activeTab, setActiveTab] = useState("freshness");

  const tabs = [
    {
      id: "freshness",
      label: "Content Freshness",
      icon: Clock,
      description: "Find and refresh stale content",
    },
    {
      id: "thin",
      label: "Thin Content",
      icon: FileText,
      description: "Expand pages with insufficient content",
    },
    {
      id: "images",
      label: "Image Optimization",
      icon: Image,
      description: "Improve alt texts and optimize images",
    },
    {
      id: "faqs",
      label: "FAQ Generation",
      icon: MessageSquare,
      description: "Create FAQs from search queries",
    },
  ];

  return (
    <div className="space-y-6">
      {/* Overview Cards */}
      <div className="grid gap-4 md:grid-cols-4">
        {tabs.map((tab) => (
          <Card
            key={tab.id}
            className={`cursor-pointer transition-colors hover:border-primary/50 ${
              activeTab === tab.id ? "border-primary" : ""
            }`}
            onClick={() => setActiveTab(tab.id)}
          >
            <CardContent className="pt-4">
              <div className="flex items-center gap-3">
                <div className="p-2 rounded-lg bg-primary/10">
                  <tab.icon className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <p className="font-medium text-sm">{tab.label}</p>
                  <p className="text-xs text-muted-foreground">
                    {tab.description}
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Info Banner */}
      <Card className="bg-muted/50 border-dashed">
        <CardContent className="pt-4">
          <div className="flex items-start gap-3">
            <Sparkles className="h-5 w-5 text-primary mt-0.5" />
            <div>
              <p className="font-medium">AI-Powered Suggestions</p>
              <p className="text-sm text-muted-foreground">
                All improvements are generated by AI and require your approval before being applied.
                Review each suggestion carefully, then click "Apply" to push changes to your store.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Tab Content */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="grid w-full grid-cols-4">
          <TabsTrigger value="freshness" className="gap-2">
            <Clock className="h-4 w-4" />
            <span className="hidden sm:inline">Freshness</span>
          </TabsTrigger>
          <TabsTrigger value="thin" className="gap-2">
            <FileText className="h-4 w-4" />
            <span className="hidden sm:inline">Thin Content</span>
          </TabsTrigger>
          <TabsTrigger value="images" className="gap-2">
            <Image className="h-4 w-4" />
            <span className="hidden sm:inline">Images</span>
          </TabsTrigger>
          <TabsTrigger value="faqs" className="gap-2">
            <MessageSquare className="h-4 w-4" />
            <span className="hidden sm:inline">FAQs</span>
          </TabsTrigger>
        </TabsList>

        <TabsContent value="freshness" className="mt-6">
          <ContentFreshnessTab storeId={storeId} />
        </TabsContent>

        <TabsContent value="thin" className="mt-6">
          <ThinContentTab storeId={storeId} />
        </TabsContent>

        <TabsContent value="images" className="mt-6">
          <ImageOptimizationTab storeId={storeId} />
        </TabsContent>

        <TabsContent value="faqs" className="mt-6">
          <FAQGenerationTab storeId={storeId} />
        </TabsContent>
      </Tabs>
    </div>
  );
}
